// i18n.js — the language layer.
//
// Two separate jobs, because the app has two kinds of text:
//
//   t(key)                  UI chrome — buttons, labels, headings that live in
//                           components. Keyed strings in ui-strings.json.
//   localiseScreen(screen)  course content — teaching prose that lives in the
//                           unit JSON. Resolved by merging a per-language
//                           overlay over the English screen.
//
// Both fall back to English when a translation is missing, per v1.1 plan §5: a
// partial translation must never break the course. A learner set to Burmese who
// opens a unit with no Burmese sees English, not blanks.
//
// What is NEVER translated: official question wording, accepted answers and
// practice options. They are verbatim USCIS text and the interview is conducted
// in English (G-3). They live in questions-uN.json, which this module does not
// touch at all.

import { derived } from 'svelte/store';
import { progress } from './stores/progress.js';
import uiStrings from './content/ui-strings.json';
import myUnit0 from './content/translations/my/unit0.json';
import myUnit1 from './content/translations/my/unit1.json';
import myUnit2 from './content/translations/my/unit2.json';
import myUnit3 from './content/translations/my/unit3.json';
import myUnit4 from './content/translations/my/unit4.json';
import myUnit5 from './content/translations/my/unit5.json';
import myUnit6 from './content/translations/my/unit6.json';
import myUnit7 from './content/translations/my/unit7.json';

// Overlays, by language then unit. Only units with a translation appear here;
// everything else resolves to English by absence.
//
// Generated by scripts/build-translations.js — never hand-edited. The generator
// refuses to emit a field the English screen does not have, or a list of the
// wrong length, so anything imported here has already been checked against the
// build it will be merged over.
const OVERLAYS = {
  my: {
    U0: myUnit0,
    U1: myUnit1,
    U2: myUnit2,
    U3: myUnit3,
    U4: myUnit4,
    U5: myUnit5,
    U6: myUnit6,
    U7: myUnit7,
  },
};

export const LANGUAGES = [
  { id: 'en', label: 'English' },
  { id: 'my', label: 'မြန်မာဘာသာ', english: 'Burmese' },
];

/** Substitute {name} placeholders. */
function interpolate(str, vars) {
  if (!vars) return str;
  return str.replace(/\{(\w+)\}/g, (whole, name) =>
    Object.prototype.hasOwnProperty.call(vars, name) ? String(vars[name]) : whole
  );
}

/**
 * UI string lookup, as a derived store so every component re-renders when the
 * language changes: `{$t('home.continue')}`.
 *
 * An unknown key returns the key itself rather than an empty string. A missing
 * translation must be VISIBLE — silent blanks are how a broken interface ships
 * looking fine.
 */
export const t = derived(progress, ($p) => {
  const lang = $p.language || 'en';
  return (key, vars) => {
    const entry = uiStrings[key];
    if (!entry) return key;
    return interpolate(entry[lang] ?? entry.en, vars);
  };
});

/**
 * Answer surfaces, which are NEVER replaced by their translation.
 *
 * Anything the learner picks as an answer stays English and gains the Burmese
 * as a secondary gloss line beneath it. The officer conducts the interview in
 * English, so an answer the learner has only ever met in Burmese is an answer
 * they cannot give — translating these away deletes the thing being practised.
 *
 * The teaching prose around them is still translated normally; this is only
 * about the things you tap.
 *
 * A second benefit falls out of it. `correctIndex` indexes into `options`, and
 * each `sortItems` entry carries the `bucket` it scores against. Because these
 * arrays are no longer touched at render, a translation can no longer shift or
 * shorten them. That is not hypothetical — a delivery of `sortItems` as plain
 * strings silently erased every bucket index in five units.
 */
const GLOSS_FIELDS = {
  options: 'optionsGloss',
  buckets: 'bucketsGloss',
  orderItems: 'orderItemsGloss',
  sortItems: 'sortItemsGloss', // list of strings, aligned by index with sortItems[].text
};

/**
 * Split overlay fields into ones that replace and ones that gloss.
 *
 * A gloss is always a flat list of strings, so the components have one contract
 * to render. `sortItems` is the exception worth naming: the English entries are
 * `{ text, bucket }` objects, and a translation of one may arrive as a bare
 * string or as an object carrying the same shape. Both reduce to the text here
 * rather than in nine template branches.
 */
function applyFields(english, fields) {
  const out = { ...english };
  for (const [key, value] of Object.entries(fields)) {
    const glossKey = GLOSS_FIELDS[key];
    if (glossKey && Array.isArray(english[key]) && Array.isArray(value)) {
      out[glossKey] = value.map((v) => (typeof v === 'string' ? v : v?.text));
    } else if (!glossKey) {
      out[key] = value;
    }
  }
  return out;
}

/**
 * Merge a language overlay over an English screen.
 *
 * Shallow by field: an overlay supplies whole values (a string, a full list),
 * never a partial one. Anything the overlay does not carry stays English.
 */
export function localiseScreen(screen, unitId, lang) {
  if (!screen || !lang || lang === 'en') return screen;
  const fields = OVERLAYS[lang]?.[unitId]?.[screen.id];
  if (!fields) return screen;

  const { items, ...rest } = fields;
  const out = applyFields(screen, rest);

  // `items` (guided practice) is a list of objects, so merge item by item
  // rather than replacing the array and losing correctIndex/kind/bucket.
  if (items && Array.isArray(screen.items)) {
    out.items = screen.items.map((item, i) => applyFields(item, items[i] || {}));
  }
  return out;
}

/** Reactive helper for components: `$localise(screen, 'U1')`. */
export const localise = derived(progress, ($p) => (screen, unitId) =>
  localiseScreen(screen, unitId, $p.language || 'en')
);

/** Which units actually have a translation in the given language. */
export function translatedUnits(lang) {
  return Object.keys(OVERLAYS[lang] || {});
}
