#!/usr/bin/env node
/**
 * image-assets.js — reconcile the artwork with the slots the course defines.
 *
 *   node scripts/image-assets.js     (npm run images)
 *
 * Writes:
 *   src/lib/content/image-manifest.json  what the app reads to tell a filled
 *                                        slot from one still waiting
 *   docs/IMAGE-ASSETS.md                 the map, and the request for the next
 *                                        batch
 *
 * Generated for the same reason as the audio map: a hand-kept list of what is
 * still missing goes stale the first time a screen changes, and then somebody
 * commissions the wrong picture.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const contentDir = join(root, 'src', 'lib', 'content');
const imageDir = join(root, 'public', 'images');
const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));

const UNITS = ['unit0', 'unit1', 'unit2', 'unit3', 'unit4', 'unit5', 'unit6', 'unit7'];

/**
 * Slots defined outside unit page data. Completion asks for a ceremony
 * photograph in its own markup rather than in JSON.
 */
const STANDALONE = [
  {
    screen: 'Completion',
    unit: 'Course completion',
    image: 'naturalization-ceremony-close.webp',
    alt: 'New citizens at a naturalization ceremony, smiling and waving small United States flags.',
  },
];

/**
 * Known problems with delivered files, recorded here so they are visible in the
 * map every time it is regenerated rather than remembered by one person.
 *
 * Keyed by filename, so replacing a file with a clean version and re-running
 * this script is all it takes to clear one.
 */
const FLAGGED = {
  'voting.webp':
    'Carries a visible "© Frame Stock Footage/Shutterstock.com" watermark — a comp preview rather than a licensed download. Replacing the file with the licensed version needs no code change; the content references it by name.',
  'civil-rights-march.webp':
    'A well-known press photograph of the civil rights movement. Confirm it is licensed for publication before this ships anywhere public.',
  'statue-of-liberty.webp':
    'A portrait photograph padded to 16:9 with blurred fill, so roughly a third of the frame is blur. A landscape crop would fill the slot properly.',
  'three-government-buildings.webp':
    'Unused. Three photographs composited into one frame, each letterboxed with blurred fill. U2-S05 uses the three clean singles instead.',
  'constitution-page-1.webp':
    'The heading reads correctly, but the cursive body text is an approximation rather than the real wording — and at 146 KB it is two and a half times the next largest file, for a parchment texture.',
};

// --- Every slot the course defines ------------------------------------------

function slots() {
  const out = [];
  for (const file of UNITS) {
    const unit = readJson(join(contentDir, `${file}.json`));
    const where = `${unit.id} — ${unit.title}`;
    for (const s of unit.screens) {
      if (s.image) out.push({ screen: s.id, unit: where, image: s.image, alt: s.alt || '' });
      for (const pic of s.imageRow || []) {
        out.push({ screen: s.id, unit: where, image: pic.image, alt: pic.alt || '', row: true });
      }
      for (const col of s.twoColumn || []) {
        if (col.image) out.push({ screen: s.id, unit: where, image: col.image, alt: col.alt || '', column: true });
      }
    }
  }
  return [...out, ...STANDALONE];
}

const onDisk = existsSync(imageDir)
  ? readdirSync(imageDir).filter((n) => /\.(webp|png|jpg|jpeg|avif)$/i.test(n))
  : [];

const all = slots();
for (const slot of all) slot.have = onDisk.includes(slot.image);

const filled = all.filter((s) => s.have);
const missing = all.filter((s) => !s.have);
const used = new Set(filled.map((s) => s.image));
const unused = onDisk.filter((n) => !used.has(n));

// --- Write -------------------------------------------------------------------

writeFileSync(
  join(contentDir, 'image-manifest.json'),
  `${JSON.stringify(
    {
      _note:
        'GENERATED by scripts/image-assets.js from what is present in public/images/. A slot whose file is absent keeps its placeholder, which states what it is waiting for rather than rendering a broken image.',
      images: onDisk.sort(),
    },
    null,
    2
  )}\n`
);

const byUnit = {};
for (const s of all) (byUnit[s.unit] ||= []).push(s);

const kb = (name) => {
  try {
    return `${(readFileSync(join(imageDir, name)).length / 1024).toFixed(0)} KB`;
  } catch {
    return '—';
  }
};

let sections = '';
for (const [unit, list] of Object.entries(byUnit)) {
  sections += `\n### ${unit}\n\n| | Screen | File | Size | Alt text |\n|---|---|---|---|---|\n`;
  for (const s of list) {
    const mark = s.have ? '●' : '○';
    const kind = s.row ? ' (row)' : s.column ? ' (column)' : '';
    sections += `| ${mark} | \`${s.screen}\`${kind} | \`${s.image}\` | ${s.have ? kb(s.image) : '—'} | ${s.alt.replace(/\|/g, '\\|')} |\n`;
  }
}

const flaggedRows = Object.entries(FLAGGED)
  .filter(([name]) => onDisk.includes(name))
  .map(([name, why]) => `| \`${name}\` | ${why} |`)
  .join('\n');

const totalKb = onDisk.reduce((n, f) => n + readFileSync(join(imageDir, f)).length, 0) / 1024;

const doc = `# Image assets — what is placed, and what is still needed

**Generated** by \`npm run images\`. Regenerate after adding or renaming a file,
or after changing a screen's image — do not edit this file.

\`●\` in place · \`○\` slot defined, no file yet

**${filled.length} of ${all.length} slots filled.** ${onDisk.length} files on disk, ${totalKb.toFixed(0)} KB total.

---

## Naming

\`\`\`
public/images/<name>.webp
\`\`\`

The content references images by filename, so the name is the contract. **Case
must match exactly** — GitHub Pages is case-sensitive and Windows is not, so
\`US-Capitol.webp\` would work on the machine that made it and 404 for every
learner. QA check 18 fails on any reference that does not resolve.

Files are 960×540. That is the \`aspect-video\` box the screens draw, and the
right pixel count for the 448px column at 2× device pixel ratio — no resizing
needed. Images are lazy-loaded, so a learner pays only for screens they reach.

Replacing a file is a drop-in: same name, no code change, then \`npm run images\`.

---

## Flagged files
${
  flaggedRows
    ? `\n| File | Note |\n|---|---|\n${flaggedRows}\n`
    : '\nNothing flagged.\n'
}
---

## Still needed — ${missing.length} slot${missing.length === 1 ? '' : 's'}

${
  missing.length
    ? `| Screen | Wanted | What it should show |\n|---|---|---|\n${missing
        .map((s) => `| \`${s.screen}\` | \`${s.image}\` | ${(s.alt || 'no alt written yet').replace(/\|/g, '\\|')} |`)
        .join('\n')}\n\nThese screens keep their placeholder, which names the file it is waiting for.`
    : 'Every slot has a file.'
}

${
  unused.length
    ? `---\n\n## On disk but unplaced — ${unused.length}\n\n${unused.map((u) => `- \`${u}\` (${kb(u)})`).join('\n')}\n`
    : ''
}
---

## Every slot
${sections}`;

writeFileSync(join(root, 'docs', 'IMAGE-ASSETS.md'), doc, 'utf8');

console.log('\nImage assets\n');
console.log(`  ${filled.length} of ${all.length} slots filled · ${onDisk.length} files · ${totalKb.toFixed(0)} KB`);
for (const s of missing) console.log(`       ○ ${s.screen} wants ${s.image}`);
for (const u of unused) console.log(`       · ${u} is on disk but unplaced`);
for (const name of Object.keys(FLAGGED)) {
  if (onDisk.includes(name)) console.log(`       ! ${name} — see docs/IMAGE-ASSETS.md`);
}
console.log('\n  src/lib/content/image-manifest.json');
console.log('  docs/IMAGE-ASSETS.md\n');
